// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WorkWell.Infrastructure.Persistence;

#nullable disable

namespace WorkWell.Infrastructure.Migrations
{
    [DbContext(typeof(WorkWellDbContext))]
    partial class WorkWellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkWell.Domain.Entities.Agenda.AgendaFuncionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("AGENDAS_FUNCIONARIOS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Agenda.ItemAgenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AgendaFuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaFuncionarioId");

                    b.ToTable("ITENS_AGENDA", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.ChatAnonimo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Anonimo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("PsicologoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("RemetenteId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("PsicologoId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("CHATS_ANONIMOS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.ConsultaPsicologica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnotacoesSigilosas")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PsicologoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("CONSULTAS_PSICOLOGICAS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.SOSemergencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAcionamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("PsicologoNotificado")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("SOS_EMERGENCIAS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AtividadesBemEstar.AtividadeBemEstar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("SetorAlvoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SetorAlvoId");

                    b.ToTable("ATIVIDADES_BEM_ESTAR", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AtividadesBemEstar.ParticipacaoAtividade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AtividadeId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("DataParticipacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Participou")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("PARTICIPACOES_ATIVIDADE", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.AvaliacaoProfunda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Gad7Score")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Interpretacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int?>("Phq9Score")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("AVALIACOES_PROFUNDAS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.MoodCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DormiuBem")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Estressado")
                        .HasColumnType("NUMBER(1)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Humor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Produtivo")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("MOOD_CHECKS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.PerfilEmocional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("HumorInicial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("PrincipaisEstressores")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Rotina")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.ToTable("PERFIS_EMOCIONAIS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.RiscoPsicossocial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("RISCOS_PSICOSSOCIAIS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("CorSecundaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("EmailAdmin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Missao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("PoliticaBemEstar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("SenhaAdmin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("TokenAcesso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("EMPRESAS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Cargo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<long>("SetorId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TokenEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SetorId");

                    b.ToTable("FUNCIONARIOS", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Setor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("SETORES", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Enquetes.Enquete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ativa")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ENQUETES", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Enquetes.RespostaEnquete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EnqueteId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("Id");

                    b.HasIndex("EnqueteId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("RESPOSTAS_ENQUETE", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Indicadores.AdesaoSetor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Adesao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<long?>("IndicadoresEmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("SetorId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("IndicadoresEmpresaId");

                    b.HasIndex("SetorId");

                    b.ToTable("ADESAO_SETOR", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Indicadores.IndicadoresEmpresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AdesaoAtividadesGeral")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<double>("FrequenciaConsultas")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("HumorMedio")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("INDICADORES_EMPRESA", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Notificacoes.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Lida")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("NOTIFICACOES", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.OmbudMind.Denuncia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoRastreamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("DenuncianteId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("FuncionarioDenuncianteId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DenuncianteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("DENUNCIAS", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.OmbudMind.InvestigacaoDenuncia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Concluida")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("DenunciaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("EquipeResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("MedidasAdotadas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DenunciaId");

                    b.ToTable("INVESTIGACOES_DENUNCIA", (string)null);
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.Psicologo", b =>
                {
                    b.HasBaseType("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario");

                    b.Property<string>("Crp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.ToTable("FUNCIONARIOS", (string)null);

                    b.HasDiscriminator().HasValue("Psicologo");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Agenda.AgendaFuncionario", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Agenda.ItemAgenda", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Agenda.AgendaFuncionario", "AgendaFuncionario")
                        .WithMany("Itens")
                        .HasForeignKey("AgendaFuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaFuncionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.ChatAnonimo", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.ApoioPsicologico.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId");

                    b.Navigation("Psicologo");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.ConsultaPsicologica", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkWell.Domain.Entities.ApoioPsicologico.Psicologo", "Psicologo")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.SOSemergencia", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AtividadesBemEstar.AtividadeBemEstar", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Setor", "SetorAlvo")
                        .WithMany()
                        .HasForeignKey("SetorAlvoId");

                    b.Navigation("Empresa");

                    b.Navigation("SetorAlvo");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AtividadesBemEstar.ParticipacaoAtividade", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.AtividadesBemEstar.AtividadeBemEstar", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.AvaliacaoProfunda", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.MoodCheck", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.PerfilEmocional", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithOne("PerfilEmocional")
                        .HasForeignKey("WorkWell.Domain.Entities.AvaliacoesEmocionais.PerfilEmocional", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.AvaliacoesEmocionais.RiscoPsicossocial", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaId");

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Setor", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", "Empresa")
                        .WithMany("Setores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Enquetes.Enquete", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Enquetes.RespostaEnquete", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Enquetes.Enquete", "Enquete")
                        .WithMany()
                        .HasForeignKey("EnqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enquete");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Indicadores.AdesaoSetor", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.Indicadores.IndicadoresEmpresa", null)
                        .WithMany("AdesaoPorSetor")
                        .HasForeignKey("IndicadoresEmpresaId");

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Indicadores.IndicadoresEmpresa", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Notificacoes.Notificacao", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.OmbudMind.Denuncia", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", "Denunciante")
                        .WithMany()
                        .HasForeignKey("DenuncianteId");

                    b.HasOne("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denunciante");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.OmbudMind.InvestigacaoDenuncia", b =>
                {
                    b.HasOne("WorkWell.Domain.Entities.OmbudMind.Denuncia", "Denuncia")
                        .WithMany()
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Agenda.AgendaFuncionario", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Empresa", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Setores");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.EmpresaOrganizacao.Funcionario", b =>
                {
                    b.Navigation("PerfilEmocional");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.Indicadores.IndicadoresEmpresa", b =>
                {
                    b.Navigation("AdesaoPorSetor");
                });

            modelBuilder.Entity("WorkWell.Domain.Entities.ApoioPsicologico.Psicologo", b =>
                {
                    b.Navigation("Atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
